Update docs describing the loggers
4Subsea/drio-python pull request #114
Opened 2023-11-02 09:53 UTC by hanne-opseth-rygg-4ss

### This PR is related to user story [ESS-2027](https://4insight.atlassian.net/jira/software/c/projects/ESS/boards/34?selectedIssue=ESS-2027)

## Description
Not sure how comprehensive the documentation should be and how detailed I should be about what the  logger actually logs? I have also deleted some of the example code that were earlier provided because i found it unnecessary to provide two examples that does the same thing, only written in different form (to some extent). 

Should I include something about the log levels or is this something they can google themselves/something we assume they already know. 

## Checklist
- [ ] PR title is descriptive and fit for injection into release notes (see tips below)
- [ ] Correct label(s) are used

2023-11-02 11:40 UTC, heidi-holm-4ss requested changes

2023-11-02 11:42 UTC, hanne-opseth-rygg-4ss commented on docs/user_guide/advanced_config.rst
> +Additionally, if you require logging for only one of the specific packages, you may use the pre-existing loggers integrated within :py:mod:`requests`, :py:mod:`oauthlib`, and :py:mod:`requests-oauthl
agree

2023-11-02 13:22 UTC, heidi-holm-4ss submitted a review, later dismissed

2023-11-02 13:22 UTC, heidi-holm-4ss commented on docs/user_guide/advanced_config.rst
> +To simplify debugging, enable logging for the logger named :py:mod:`datareservoirio`. This is especially helpful if you experience undesired behavior in your application.
on this line we don't refer to the module but the logger. So here I believe we should skip pymod

2023-11-02 13:22 UTC, heidi-holm-4ss commented on docs/user_guide/advanced_config.rst
> +provided code. Additionally, if you require logging for only one of the specific packages, you may use the pre-existing loggers integrated within :py:mod:`requests`, :py:mod:`oauthlib`, and :py:mod:`
Drop Additionally - just start sentence with If.

2023-11-06 09:01 UTC, heidi-holm-4ss approved these changes

2023-11-06 11:04 UTC, merged