Test _blob_to_df
4Subsea/drio-python pull request #57
Opened 2023-03-06 11:49 UTC by vegard-solum-4ss

### This PR is related to user story DST-432

## Description
Started setting up a mocking framework + add tests for the `_blob_to_df()` function.

## Checklist
- [ ] PR title is descriptive and fit for injection into release notes (see tips below)
- [ ] Correct label(s) are used

PR title tips:
* Use imperative mood
* Describe the motivation for change, issue that has been solved or what has been improved - not how
* Examples:
  * Add functionality for Allan variance to sensor_4s.simulate
  * Upgrade to support Python 9.10
  * Remove MacOS from CI

2023-03-07 11:38 UTC, katarina-vardic-4ss reviewed
Changed URI to include "http:" part

2023-03-10 12:25 UTC, ace-e4s requested changes

2023-03-10 12:25 UTC, ace-e4s commented on tests/conftest.py
> +    response.mock_calls = call(*args, **kwargs)
```suggestion
    response.mock_calls = call(method, url, *args, **kwargs)
```

2023-03-10 12:39 UTC, ace-e4s approved these changes

2023-03-10 12:43 UTC, merged