Update packaging to latest standards
4Subsea/drio-python pull request #62
Opened 2023-03-09 11:37 UTC by vegard-solum-4ss

### This PR is related to user story DST-439

## Description
Updated the packaging setup to the latest standards.

## Checklist
- [x] PR title is descriptive and fit for injection into release notes (see tips below)
- [x] Correct label(s) are used

PR title tips:
* Use imperative mood
* Describe the motivation for change, issue that has been solved or what has been improved - not how
* Examples:
  * Add functionality for Allan variance to sensor_4s.simulate
  * Upgrade to support Python 9.10
  * Remove MacOS from CI

2023-03-09 20:35 UTC, ace-e4s requested changes
This PR do not work as-is, since code is not inside `src` folder. Either this has to be done in this PR as well, or `pyproject` must be configured properly.

I suggest doing the former, i.e. `src` folder.

2023-03-10 08:00 UTC, vegard-solum-4ss commented
Why will it not work?

2023-03-10 09:45 UTC, ace-e4s commented
Is it possible to add this part from `setup.cfg` into `pyproject.toml` ?

```
[options]
packages = find_namespace:
python_requires = >=3.8
install_requires =
    numpy
    oauthlib
    pandas
    pyarrow
    requests
    requests-oauthlib
    importlib_resources

[options.packages.find]
include =
    datareservoirio
    datareservoirio.*
```

This is not ported over to `pyproject` it seems. This will cause issues if you have any other folders in the root folder.

2023-03-10 10:03 UTC, ace-e4s approved these changes

2023-03-10 10:28 UTC, merged