Added timer decorator
4Subsea/drio-python pull request #63
Opened 2023-03-10 09:01 UTC by ali-amin-ahmad-4ss

### This PR is related to user story DATARES-361(https://4insight.atlassian.net/browse/DATARES-361)

## Description
Added end-to-end measurement latency when getting timeseries

2023-03-13 12:57 UTC, vegard-solum-4ss commented on datareservoirio/client.py
> +    def timer(func):
Rename the timer to `_timer` (with an underscore), so that it is hidden for the user

2023-03-13 12:57 UTC, vegard-solum-4ss commented on datareservoirio/client.py
> +    @staticmethod
Remove `@staticmethod`

2023-03-13 13:00 UTC, vegard-solum-4ss commented
Remove the setup.cfg file. The content of this file has been moved to the pyproject.toml file

2023-03-13 13:56 UTC, vegard-solum-4ss approved these changes
Looks good!

2023-03-14 13:20 UTC, ace-e4s requested changes

2023-03-14 13:20 UTC, ace-e4s commented on tests/conftest.py
> +    monkeypatch.setattr(drio.client, "AzureLogHandler", logging.NullHandler())
```suggestion
    monkeypatch.setattr("drio.client.AzureLogHandler", logging.NullHandler())
```

2023-03-14 13:20 UTC, ace-e4s commented on tests/conftest.py
> +import datareservoirio as drio
```suggestion
```

2023-03-14 13:20 UTC, ace-e4s commented on tests/conftest.py
> +
```suggestion
```

2023-03-14 13:26 UTC, ace-e4s submitted a review, later dismissed

2023-03-14 13:28 UTC, ace-e4s requested changes

2023-03-14 13:28 UTC, ace-e4s commented on tests/conftest.py
> +    monkeypatch.setattr("drio.client.AzureLogHandler", logging.NullHandler())
```suggestion
    monkeypatch.setattr("datareservoirio.client.AzureLogHandler", logging.NullHandler())
```

2023-03-14 13:34 UTC, vegard-solum-4ss approved these changes

2023-03-14 13:35 UTC, vegard-solum-4ss approved these changes

2023-03-14 13:39 UTC, merged